name: deploy to S3 

on: 
  workflow_dispatch:


jobs: 
  build-personalwebsite:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps: 
      - name: checkout code 
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install required dependencies 
        run: npm install 
      - name: Build app 
        run: npm run build
      - name: Configure Aws Cred 
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Synce to aws S3
        run:  aws s3 sync ./build/ s3://${{ secrets.BUCKET_NAME }}
